<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.daninichu</groupId>
    <artifactId>myutils</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <gdx.version>1.13.5</gdx.version>
        <libgdx.version>1.13.1</libgdx.version>

    </properties>

    <dependencies>
        <!-- JUnit-->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.5.2</version>
            <scope>test</scope>
        </dependency>

        <!-- JMH-->
        <dependency>
            <groupId>org.openjdk.jmh</groupId>
            <artifactId>jmh-core</artifactId>
            <version>1.37</version>
        </dependency>
        <dependency>
            <groupId>org.openjdk.jmh</groupId>
            <artifactId>jmh-generator-annprocess</artifactId>
            <version>1.37</version>
        </dependency>

        <dependency>
            <!--libGDX graphics library – https://libgdx.com/ -->
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx</artifactId>
            <version>${libgdx.version}</version>
        </dependency>
        <dependency>
            <!-- Platform-specific libraries -->
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx-platform</artifactId>
            <version>${libgdx.version}</version>
            <classifier>natives-desktop</classifier>
        </dependency>
        <dependency>
            <!-- libgdx OpenGL backend-->
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx-backend-lwjgl3</artifactId>
            <version>${libgdx.version}</version>
        </dependency>
        <dependency>
            <!-- run libgdx without graphics (for testing)-->
            <groupId>com.badlogicgames.gdx</groupId>
            <artifactId>gdx-backend-headless</artifactId>
            <version>${libgdx.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>
</project>